### ISSUE TITLE
Where is p65.py ?

### ISSUE THREAD

**Issue by ghost** [michaelcmartin/Ophis#30]
Trying to setup Swift on PC to do some BBC assembler - Swift guide says use p65.py but it's not in latest archive, or if it is I can't find it?

Swift reference points to http://hkn.berkeley.edu/~mcmartin/P65 which is now dead.

I tried http://hkn.berkeley.edu/~mcmartin/P65 in the internet archive but that only let me get my hands on ophis 1.0 and even that didnt have p65.py in.

The Swift reference is pointing to P65-Ophis-0.7.2

Thanks

**Comment by michaelcmartin** [comment]
Sounds like the Swift guide is very old. P65 was the old (like, nearly 20 years ago) name for Ophis. I changed the name because it kept conflicting with PageMaker file extensions.

If you're running on Windows, you should be able to run the latest Ophis installer, point Swift to ophis.exe instead of p65.exe, and have no issues.

(I'm basing this on the links at http://www.retrosoftware.co.uk/wiki/index.php?title=SWIFT#Links - the link there is to the 1.0 version on the old site, and a quick check of the tutorial suggests that it is not using any of the aspects of 0.7.2 that were deprecated in 1.0 and removed in 2.0.)
